item {
  name: "kantung_mata_kanan"
  id: 1
}
item {
  name: "kantung_mata_kiri"
  id: 2
}
item {
  name: "mata_merah_kanan"
  id: 3
}
item {
  name: "mata_merah_kiri"
  id: 4
}
item {
  name: "mata_normal_kanan"
  id: 5
}
item {
  name: "mata_normal_kiri"
  id: 6
}
